#!/usr/bin/env node
/**
 * split-i18n.cjs
 *
 * Reads hlc-app/recipes.js (window.HLC_RECIPES = [ ...51 recipes, each with an
 * inline i18n{} of 6 translated languages... ];) and splits it into:
 *
 *   - recipes-i18n.js  -> window.HLC_I18N = { "<recipe-id>": {pt,es,it,zh,hi,he}, ... };
 *   - recipes.base.js  -> window.HLC_RECIPES = [ ...same recipes, i18n field removed... ];
 *                         (the future slim recipes.js, loaded for English users)
 *
 * Does NOT modify recipes.js, app.js, index.html, or i18n.js. Safe to re-run.
 *
 * Usage: node scripts/split-i18n.cjs
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "recipes.js");
const OUT_I18N = path.join(ROOT, "recipes-i18n.js");
const OUT_BASE = path.join(ROOT, "recipes.base.js");

function main() {
  const raw = fs.readFileSync(SRC, "utf8");

  // Extract the array literal via first "[" .. last "]" in the file.
  const start = raw.indexOf("[");
  const end = raw.lastIndexOf("]");
  if (start === -1 || end === -1 || end < start) {
    throw new Error("Could not locate array literal ([ ... ]) in " + SRC);
  }
  const arrayText = raw.slice(start, end + 1);

  /** @type {Array<Record<string, any>>} */
  const recipes = JSON.parse(arrayText);

  const i18nMap = {};
  const baseRecipes = [];

  for (const recipe of recipes) {
    const { i18n, ...rest } = recipe;
    if (recipe.id === undefined) {
      throw new Error("Recipe missing 'id' field: " + JSON.stringify(recipe).slice(0, 120));
    }
    if (i18n !== undefined) {
      i18nMap[recipe.id] = i18n;
    }
    baseRecipes.push(rest);
  }

  const i18nOut =
    "// AUTO-GENERATED by scripts/split-i18n.cjs — do not edit by hand.\n" +
    "// Per-recipe translated display fields, keyed by recipe id.\n" +
    "// Loaded lazily/only for the active non-English language.\n" +
    "window.HLC_I18N = " + JSON.stringify(i18nMap, null, 2) + ";\n";

  const baseOut =
    "// AUTO-GENERATED by scripts/split-i18n.cjs — do not edit by hand.\n" +
    "// Same recipes as recipes.js, with the inline i18n{} field removed.\n" +
    "// Intended as the future slim recipes.js for English-only initial load.\n" +
    "window.HLC_RECIPES = " + JSON.stringify(baseRecipes, null, 2) + ";\n";

  fs.writeFileSync(OUT_I18N, i18nOut, "utf8");
  fs.writeFileSync(OUT_BASE, baseOut, "utf8");

  const idCount = Object.keys(i18nMap).length;
  const langCounts = Object.values(i18nMap).map((v) => Object.keys(v).length);
  const minLangs = langCounts.length ? Math.min(...langCounts) : 0;
  const maxLangs = langCounts.length ? Math.max(...langCounts) : 0;

  console.log("Recipes parsed:        " + recipes.length);
  console.log("Recipes with i18n:     " + idCount);
  console.log("Recipes in base file:  " + baseRecipes.length);
  console.log("Languages per recipe:  min=" + minLangs + " max=" + maxLangs);
  console.log("Wrote: " + path.relative(ROOT, OUT_I18N));
  console.log("Wrote: " + path.relative(ROOT, OUT_BASE));
}

main();
